welcome_message: "Welcome to Ladies' Bible Study. <br>
Below you will have access to previous lessons with new lessons added weekly."

semester_previous_title: "Last Semester: Growing in Sanctification"
semester_current_title: "This Semester"

charts_previous_url: "/assets/pdfs/charts.pdf"
charts_current:
  - title: "Sit, Walk, Stand Chart"
    file: /assets/pdfs/sit-walk-stand.pdf
  - title: "Body, Soul, Spirit Chart"
    file: /assets/pdfs/mind-heart-spirit.pdf
  - title: "C.L.A.S.H. Chart"
    file: /assets/pdfs/CLASH.pdf
  - title: "Heart to Consequences Chart"
    file: /assets/pdfs/heart-to-consequences-chart.pdf
