welcome_message: "Welcome to Ladies Bible Study. Below you will have access to previous lessons with new lessons added weekly."
semester_previous_title: "Last Semester: Growing in Sanctification"
semester_current_title: "This Semester"

charts_previous_url: "/assets/pdfs/charts.pdf"
charts_current_url: "/assets/pdfs/charts.pdf"
