welcome_message: "Welcome to Ladies Bible Study. Edit this message anytime in _data/site.yml."
semester_previous_title: "Last Semester"
semester_current_title: "This Semester"

charts_previous_url: "#"
charts_current_url: "#"
